# Generated by Django 4.2.4 on 2023-08-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('content', models.TextField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(choices=[('TECH', 'Tech'), ('EBOOK', 'Ebook'), ('ON_COURSE', 'Online Course'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('link', models.URLField(max_length=300)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
